Dice game example
open-telemetry/opentelemetry-erlang-contrib pull request #173
Opened 2023-05-18 03:46 UTC by marcdel

Adds a dice game example in service of this documentation pull request: https://github.com/open-telemetry/opentelemetry.io/pull/2685

2023-05-31 06:45 UTC, benregn commented
It's because Phoenix now vendors all the icons from https://heroicons.com/ for newly generated projects. I assume they could be trimmed back since probably only a handful of icons (maybe?) are used in this project 🙂

2023-05-31 11:19 UTC, tsloughter commented
None should be used in this project, so they can all be removed.

2023-06-14 04:39 UTC, benregn commented
@lessless I'm not the author of this PR but thanks for the suggestion. 

However in my opinion, an example using Phoenix is probably more helpful because it's used more in the wild.

2023-06-16 11:08 UTC, tsloughter approved these changes
I'll merge once the unnecessary files, like icons are removed.

2023-07-07 19:38 UTC, tsloughter commented
@marcdel ping

2023-10-06 21:24 UTC, marcdel commented
@tsloughter sorry, I totally spaced on this. I regenerated the app without all the html stuff which simplifies it significantly. Happy to add metrics examples as well, but probably as a separate PR.

2023-10-07 11:27 UTC, tsloughter commented on examples/roll_dice/README.md
> +      Tracer.set_attribute(:roll, roll)
```suggestion
      Tracer.set_attribute(:"roll.value", roll)
```

2023-10-07 11:28 UTC, tsloughter requested changes
Looks good! Just had one change to match the other implementations of the example in other languages.

2023-10-07 11:29 UTC, tsloughter commented
Thanks! Sounds good with having another PR.

2023-10-17 19:46 UTC, marcdel commented
@tsloughter boop! rebased this guy, so should be good to go.

2023-10-27 18:39 UTC, tsloughter approved these changes

2023-10-27 19:23 UTC, merged